### ISSUE TITLE
List rendering issue?

### ISSUE THREAD

**Issue by staxmanade** [thlorenz/hermit#2]
Hello,

taking a quick look at the library and noticed that lists appear to be rendering, but I cannot see the text.
### iTerm2

![screenshot](http://cl.ly/image/3K0X0V3H0w0g/Image%202014-06-08%20at%209.54.27%20PM.png)
### Terminal

![screenshot2](http://cl.ly/image/2D3C2a2a0X00/Image%202014-06-08%20at%209.57.11%20PM.png)
### Sample code to generate

```
var hermit = require('hermit')
  , html = '<ul><li>An item in a bulleted (unordered) list<ul><li>A subitem, indented with 4 spaces</li></ul></li><li>Another item in a bulleted list  </li></ul>';

hermit(html, function (err, res) {
  console.log(res);
});
```

Any thoughts? Thanks.

**Comment by thlorenz** [comment]
Yeah, it's not perfect, but if you put `span` elements around the text it works better.

``` js
var hermit = require('hermit')
  , html = [
      '<ul>'
    , '  <li><span>An item in a bulleted (unordered) list</span></li>'
    , '  <li>'
    , '   <ul>'
    , '      <li><span>A subitem, indented with 4 spaces</span></li>'
    , '    </ul>'
    , '   </li>'
    , '   <li><span>Another item in a bulleted list</span></li>'
    , '</ul>'
  ].join('\n');

hermit(html, function (err, res) {
    console.log(res);
});
```

I never encountered this problem, so seems like it's rare to have text directly inside an `<li>`. Keep in mind this is not meant to be a browser replacement. I created it for [replpad](http://thlorenz.github.io/replpad/) to render small documentation html snippets.

**Comment by staxmanade** [comment]
The use case I was trying to get going, was creating markdown help for a command line tool, using marked to render it and tried this tool to render the markdown HTML. (A few too many translation layers, but thought it might be a quick win.)

**Comment by thlorenz** [comment]
Actually have a look at [msee](https://github.com/firede/msee) for that. I'm using that in replpad to render documentation of modules you require. It even highlights code sections with [cardinal](https://github.com/thlorenz/cardinal) (as long as they are javascript).

**Comment by staxmanade** [comment]
I knew this had to be a problem someone already solved... Thanks for that tip!
